#!/bin/sh

export NNN_OPTS=xUdHEA
export NNN_BMS="b:$HOME;c:$XDG_CONFIG_HOME;d:$HOME/doc;m:/media;w:$HOME/www"
export NNN_PLUG="v:imgview"
export NNN_COLORS="#09090909"
export NNN_FCOLORS="0000090a00000000000000"
